### ISSUE TITLE
QR Code Button crashes the app

### ISSUE THREAD

**Issue by Sanjit1** [frc-emotion/Android-Scouter#6]
The QR Code Button does not generate a code, it just goes blank

**Comment by Sanjit1** [comment]
Process: com.gsnathan.android_scouter, PID: 12930
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.StringBuilder.toString()' on a null object reference
Here is the error llog if that helps

**Comment by JavaCafe01** [comment]
You must have data saved for the qr code to work. I have not made a user dialog for permissions yet, so you will have to manually give it storage permissions through settings. Then, fill up and save some data. Make sure there is a file in your downloads folder called `scouter_data.csv`. Then you can generate qr codes.
